package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"fmt"
	"witness/graphql/generated"
	"witness/models"
)

// Details is the resolver for the details field.
func (r *auditEventResolver) Details(ctx context.Context, obj *models.AuditEvent) (*string, error) {
	panic(fmt.Errorf("not implemented: Details - details"))
}

// AuditEvent returns generated.AuditEventResolver implementation.
func (r *Resolver) AuditEvent() generated.AuditEventResolver { return &auditEventResolver{r} }

type auditEventResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
